/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2023-07-17 04:57:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modifyGoodsForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/Documents/workspace-sts-3.9.18.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1688950375518L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/Documents/workspace-sts-3.9.18.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function fn_modify_goods(goods_id, attribute){\r\n");
      out.write("	var frm_mod_goods=document.frm_mod_goods;\r\n");
      out.write("	var value=\"\";\r\n");
      out.write("	if(attribute=='goods_sort'){\r\n");
      out.write("		value=frm_mod_goods.goods_sort.value;\r\n");
      out.write("	}else if(attribute=='goods_title'){\r\n");
      out.write("		value=frm_mod_goods.goods_title.value;\r\n");
      out.write("	}else if(attribute=='goods_writer'){\r\n");
      out.write("		value=frm_mod_goods.goods_writer.value;   \r\n");
      out.write("	}else if(attribute=='goods_publisher'){\r\n");
      out.write("		value=frm_mod_goods.goods_publisher.value;\r\n");
      out.write("	}else if(attribute=='goods_price'){\r\n");
      out.write("		value=frm_mod_goods.goods_price.value;\r\n");
      out.write("	}else if(attribute=='goods_sales_price'){\r\n");
      out.write("		value=frm_mod_goods.goods_sales_price.value;\r\n");
      out.write("	}else if(attribute=='goods_point'){\r\n");
      out.write("		value=frm_mod_goods.goods_point.value;\r\n");
      out.write("	}else if(attribute=='goods_published_date'){\r\n");
      out.write("		value=frm_mod_goods.goods_published_date.value;\r\n");
      out.write("	}else if(attribute=='goods_page_total'){\r\n");
      out.write("		value=frm_mod_goods.goods_page_total.value;\r\n");
      out.write("	}else if(attribute=='goods_isbn'){\r\n");
      out.write("		value=frm_mod_goods.goods_isbn.value;\r\n");
      out.write("	}else if(attribute=='goods_delivery_price'){\r\n");
      out.write("		value=frm_mod_goods.goods_delivery_price.value;\r\n");
      out.write("	}else if(attribute=='goods_delivery_date'){\r\n");
      out.write("		value=frm_mod_goods.goods_delivery_date.value;\r\n");
      out.write("	}else if(attribute=='goods_status'){\r\n");
      out.write("		value=frm_mod_goods.goods_status.value;\r\n");
      out.write("	}else if(attribute=='goods_contents_order'){\r\n");
      out.write("		value=frm_mod_goods.goods_contents_order.value;\r\n");
      out.write("	}else if(attribute=='goods_writer_intro'){\r\n");
      out.write("		value=frm_mod_goods.goods_writer_intro.value;\r\n");
      out.write("	}else if(attribute=='goods_intro'){\r\n");
      out.write("		value=frm_mod_goods.goods_intro.value;\r\n");
      out.write("	}else if(attribute=='publisher_comment'){\r\n");
      out.write("		value=frm_mod_goods.publisher_comment.value;\r\n");
      out.write("	}else if(attribute=='recommendation'){\r\n");
      out.write("		value=frm_mod_goods.recommendation.value;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : \"post\",\r\n");
      out.write("		async : false, //false인 경우 동기식으로 처리한다.\r\n");
      out.write("		url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/goods/modifyGoodsInfo.do\",\r\n");
      out.write("		data : {\r\n");
      out.write("			goods_id:goods_id,\r\n");
      out.write("			attribute:attribute,\r\n");
      out.write("			value:value\r\n");
      out.write("		},\r\n");
      out.write("		success : function(data, textStatus) {\r\n");
      out.write("			if(data.trim()=='mod_success'){\r\n");
      out.write("				alert(\"상품 정보를 수정했습니다.\");\r\n");
      out.write("			}else if(data.trim()=='failed'){\r\n");
      out.write("				alert(\"다시 시도해 주세요.\");	\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error : function(data, textStatus) {\r\n");
      out.write("			alert(\"에러가 발생했습니다.\"+data);\r\n");
      out.write("		},\r\n");
      out.write("		complete : function(data, textStatus) {\r\n");
      out.write("			//alert(\"작업을완료 했습니다\");\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	}); //end ajax	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  function readURL(input,preview) {\r\n");
      out.write("	//  alert(preview);\r\n");
      out.write("    if (input.files && input.files[0]) {\r\n");
      out.write("        var reader = new FileReader();\r\n");
      out.write("        reader.onload = function (e) {\r\n");
      out.write("            $('#'+preview).attr('src', e.target.result);\r\n");
      out.write("        }\r\n");
      out.write("        reader.readAsDataURL(input.files[0]);\r\n");
      out.write("    }\r\n");
      out.write("  }  \r\n");
      out.write("\r\n");
      out.write("  var cnt =1;\r\n");
      out.write("  function fn_addFile(){\r\n");
      out.write("	  $(\"#d_file\").append(\"<br>\"+\"<input  type='file' name='detail_image\"+cnt+\"' id='detail_image\"+cnt+\"'  onchange=readURL(this,'previewImage\"+cnt+\"') />\");\r\n");
      out.write("	  $(\"#d_file\").append(\"<img  id='previewImage\"+cnt+\"'   width=200 height=200  />\");\r\n");
      out.write("	  $(\"#d_file\").append(\"<input  type='button' value='추가'  onClick=addNewImageFile('detail_image\"+cnt+\"','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imageFileList[0].goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','detail_image')  />\");\r\n");
      out.write("	  cnt++;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function modifyImageFile(fileId,goods_id, image_id,fileType){\r\n");
      out.write("    // alert(fileId);\r\n");
      out.write("	  var form = $('#FILE_FORM')[0];\r\n");
      out.write("      var formData = new FormData(form);\r\n");
      out.write("      formData.append(\"fileName\", $('#'+fileId)[0].files[0]);\r\n");
      out.write("      formData.append(\"goods_id\", goods_id);\r\n");
      out.write("      formData.append(\"image_id\", image_id);\r\n");
      out.write("      formData.append(\"fileType\", fileType);\r\n");
      out.write("      \r\n");
      out.write("      $.ajax({\r\n");
      out.write("        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/goods/modifyGoodsImageInfo.do',\r\n");
      out.write("        processData: false,\r\n");
      out.write("        contentType: false,\r\n");
      out.write("        data: formData,\r\n");
      out.write("        type: 'POST',\r\n");
      out.write("	      success: function(result){\r\n");
      out.write("	         alert(\"이미지를 수정했습니다!\");\r\n");
      out.write("	       }\r\n");
      out.write("      });\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function addNewImageFile(fileId,goods_id, fileType){\r\n");
      out.write("	   //  alert(fileId);\r\n");
      out.write("		  var form = $('#FILE_FORM')[0];\r\n");
      out.write("	      var formData = new FormData(form);\r\n");
      out.write("	      formData.append(\"uploadFile\", $('#'+fileId)[0].files[0]);\r\n");
      out.write("	      formData.append(\"goods_id\", goods_id);\r\n");
      out.write("	      formData.append(\"fileType\", fileType);\r\n");
      out.write("	      \r\n");
      out.write("	      $.ajax({\r\n");
      out.write("	          url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/goods/addNewGoodsImage.do',\r\n");
      out.write("	                  processData: false,\r\n");
      out.write("	                  contentType: false,\r\n");
      out.write("	                  data: formData,\r\n");
      out.write("	                  type: 'post',\r\n");
      out.write("	                  success: function(result){\r\n");
      out.write("	                      alert(\"이미지를 수정했습니다!\");\r\n");
      out.write("	                  }\r\n");
      out.write("	          });\r\n");
      out.write("	  }\r\n");
      out.write("  \r\n");
      out.write("  function deleteImageFile(goods_id,image_id,imageFileName,trId){\r\n");
      out.write("	var tr = document.getElementById(trId);\r\n");
      out.write("\r\n");
      out.write("      	$.ajax({\r\n");
      out.write("    		type : \"post\",\r\n");
      out.write("    		async : true, //false인 경우 동기식으로 처리한다.\r\n");
      out.write("    		url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/goods/removeGoodsImage.do\",\r\n");
      out.write("    		data: {goods_id:goods_id,\r\n");
      out.write("     	         image_id:image_id,\r\n");
      out.write("     	         imageFileName:imageFileName},\r\n");
      out.write("    		success : function(data, textStatus) {\r\n");
      out.write("    			alert(\"이미지를 삭제했습니다!!\");\r\n");
      out.write("                tr.style.display = 'none';\r\n");
      out.write("    		},\r\n");
      out.write("    		error : function(data, textStatus) {\r\n");
      out.write("    			alert(\"에러가 발생했습니다.\"+textStatus);\r\n");
      out.write("    		},\r\n");
      out.write("    		complete : function(data, textStatus) {\r\n");
      out.write("    			//alert(\"작업을완료 했습니다\");\r\n");
      out.write("    			\r\n");
      out.write("    		}\r\n");
      out.write("    	}); //end ajax	\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY>\r\n");
      out.write("<form  name=\"frm_mod_goods\"  method=post >\r\n");
      out.write("<DIV class=\"clear\"></DIV>\r\n");
      out.write("	<!-- 내용 들어 가는 곳 -->\r\n");
      out.write("	<DIV id=\"container\">\r\n");
      out.write("		<UL class=\"tabs\">\r\n");
      out.write("			<li><A href=\"#tab1\">상품정보</A></li>\r\n");
      out.write("			<li><A href=\"#tab2\">상품목차</A></li>\r\n");
      out.write("			<li><A href=\"#tab3\">상품저자소개</A></li>\r\n");
      out.write("			<li><A href=\"#tab4\">상품소개</A></li>\r\n");
      out.write("			<li><A href=\"#tab5\">출판사 상품 평가</A></li>\r\n");
      out.write("			<li><A href=\"#tab6\">추천사</A></li>\r\n");
      out.write("			<li><A href=\"#tab7\">상품이미지</A></li>\r\n");
      out.write("		</UL>\r\n");
      out.write("		<DIV class=\"tab_container\">\r\n");
      out.write("			<DIV class=\"tab_content\" id=\"tab1\">\r\n");
      out.write("				<table >\r\n");
      out.write("			<tr >\r\n");
      out.write("				<td width=200 >상품분류</td>\r\n");
      out.write("				<td width=500>\r\n");
      out.write("				  <select name=\"goods_sort\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td >\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_sort')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr >\r\n");
      out.write("				<td >상품이름</td>\r\n");
      out.write("				<td><input name=\"goods_title\" type=\"text\" size=\"40\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_title')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >저자</td>\r\n");
      out.write("				<td><input name=\"goods_writer\" type=\"text\" size=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("								<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_writer')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >출판사</td>\r\n");
      out.write("				<td><input name=\"goods_publisher\" type=\"text\" size=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_publisher }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("			     <td>\r\n");
      out.write("				  <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_publisher')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >상품정가</td>\r\n");
      out.write("				<td><input name=\"goods_price\" type=\"text\" size=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_price')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >상품판매가격</td>\r\n");
      out.write("				<td><input name=\"goods_sales_price\" type=\"text\" size=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_sales_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_sales_price')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >상품 구매 포인트</td>\r\n");
      out.write("				<td><input name=\"goods_point\" type=\"text\" size=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_point }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_point')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >상품출판일</td>\r\n");
      out.write("				<td>\r\n");
      out.write("				  <input  name=\"goods_published_date\"  type=\"date\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_published_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_published_date')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >상품 총 페이지수</td>\r\n");
      out.write("				<td><input name=\"goods_total_page\" type=\"text\" size=\"40\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_total_page }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_total_page\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >ISBN</td>\r\n");
      out.write("				<td><input name=\"goods_isbn\" type=\"text\" size=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_isbn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_isbn')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >상품 배송비</td>\r\n");
      out.write("				<td><input name=\"goods_delivery_price\" type=\"text\" size=\"40\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_delivery_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_delivery_price')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >상품 도착 예정일</td>\r\n");
      out.write("				<td>\r\n");
      out.write("				  <input name=\"goods_delivery_date\" type=\"date\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_delivery_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("				  </td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_delivery_date')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >상품종류</td>\r\n");
      out.write("				<td>\r\n");
      out.write("				<select name=\"goods_status\">\r\n");
      out.write("				  <option value=\"bestseller\"  >베스트셀러</option>\r\n");
      out.write("				  <option value=\"steadyseller\" >스테디셀러</option>\r\n");
      out.write("				  <option value=\"newbook\" >신간</option>\r\n");
      out.write("				  <option value=\"on_sale\" >판매중</option>\r\n");
      out.write("				  <option value=\"buy_out\"  selected>품절</option>\r\n");
      out.write("				  <option value=\"out_of_print\" >절판</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				<input  type=\"hidden\" name=\"h_goods_status\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_status }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>\r\n");
      out.write("				 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_status')\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			 <td colspan=3>\r\n");
      out.write("			   <br>\r\n");
      out.write("			 </td>\r\n");
      out.write("			</tr>\r\n");
      out.write("				</table>	\r\n");
      out.write("			</DIV>\r\n");
      out.write("			<DIV class=\"tab_content\" id=\"tab2\">\r\n");
      out.write("				<h4>책목차</h4>\r\n");
      out.write("				<table>	\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td >상품목차</td>\r\n");
      out.write("					<td><textarea  rows=\"100\" cols=\"80\" name=\"goods_contents_order\">\r\n");
      out.write("					  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_contents_order }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					</textarea>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("					&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("					 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_contents_order')\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				</table>	\r\n");
      out.write("			</DIV>\r\n");
      out.write("			<DIV class=\"tab_content\" id=\"tab3\">\r\n");
      out.write("				<H4>상품 저자 소개</H4>\r\n");
      out.write("				<P>\r\n");
      out.write("				 <table>\r\n");
      out.write("	  				 <tr>\r\n");
      out.write("						<td >상품 저자 소개</td>\r\n");
      out.write("						<td><textarea  rows=\"100\" cols=\"80\" name=\"goods_writer_intro\">\r\n");
      out.write("						  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_writer_intro }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						</textarea>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_writer_intro')\"/>\r\n");
      out.write("						</td>\r\n");
      out.write("				   </tr>\r\n");
      out.write("			   </table>\r\n");
      out.write("				</P>\r\n");
      out.write("			</DIV>\r\n");
      out.write("			<DIV class=\"tab_content\" id=\"tab4\">\r\n");
      out.write("				<H4>상품소개</H4>\r\n");
      out.write("				<P>\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>상품소개</td>\r\n");
      out.write("						<td><textarea  rows=\"100\" cols=\"80\" name=\"goods_intro\">\r\n");
      out.write("						");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_intro }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						</textarea>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_intro')\"/>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("			    </table>\r\n");
      out.write("				</P>\r\n");
      out.write("			</DIV>\r\n");
      out.write("			<DIV class=\"tab_content\" id=\"tab5\">\r\n");
      out.write("				<H4>출판사 상품 평가</H4>\r\n");
      out.write("				<P>\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td><textarea  rows=\"100\" cols=\"80\" name=\"goods_publisher_comment\">\r\n");
      out.write("						  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_publisher_comment }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						</textarea>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_publisher_comment')\"/>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("				</P>\r\n");
      out.write("			</DIV>\r\n");
      out.write("			<DIV class=\"tab_content\" id=\"tab6\">\r\n");
      out.write("				<H4>추천사</H4>\r\n");
      out.write("				 <table>\r\n");
      out.write("					 <tr>\r\n");
      out.write("						<td>추천사</td>\r\n");
      out.write("						<td><textarea  rows=\"100\" cols=\"80\" name=\"goods_recommendation\">\r\n");
      out.write("						  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_recommendation }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						</textarea>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("						 <input  type=\"button\" value=\"수정반영\"  onClick=\"fn_modify_goods('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','goods_recommendation')\"/>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("			    </table>\r\n");
      out.write("			</DIV>\r\n");
      out.write("			<DIV class=\"tab_content\" id=\"tab7\">\r\n");
      out.write("			   <form id=\"FILE_FORM\" method=\"post\" enctype=\"multipart/form-data\"  >\r\n");
      out.write("				<h4>상품이미지</h4>\r\n");
      out.write("				 <table>\r\n");
      out.write("					 <tr>\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			    <tr align=\"center\">\r\n");
      out.write("			      <td colspan=\"3\">\r\n");
      out.write("				      <div id=\"d_file\">\r\n");
      out.write("						  ");
      out.write("\r\n");
      out.write("				      </div>\r\n");
      out.write("			       </td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("		   <tr>\r\n");
      out.write("		     <td align=center colspan=2>\r\n");
      out.write("		     \r\n");
      out.write("		     <input   type=\"button\" value=\"이미지파일추가하기\"  onClick=\"fn_addFile()\"  />\r\n");
      out.write("		   </td>\r\n");
      out.write("		</tr> \r\n");
      out.write("	</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	</DIV>\r\n");
      out.write("	<DIV class=\"clear\"></DIV>\r\n");
      out.write("					\r\n");
      out.write("</form>	");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/goods/modifyGoodsForm.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("goods");
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/goods/modifyGoodsForm.jsp(7,0) '${goodsMap.goods}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${goodsMap.goods}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("imageFileList");
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/goods/modifyGoodsForm.jsp(8,0) '${goodsMap.imageFileList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${goodsMap.imageFileList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(11,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty goods.goods_status}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<script>\r\n");
          out.write("window.onload=function()\r\n");
          out.write("{\r\n");
          out.write("	init();\r\n");
          out.write("}\r\n");
          out.write("\r\n");
          out.write("function init(){\r\n");
          out.write("	var frm_mod_goods=document.frm_mod_goods;\r\n");
          out.write("	var h_goods_status=frm_mod_goods.h_goods_status;\r\n");
          out.write("	var goods_status=h_goods_status.value;\r\n");
          out.write("	var select_goods_status=frm_mod_goods.goods_status;\r\n");
          out.write("	 select_goods_status.value=goods_status;\r\n");
          out.write("}\r\n");
          out.write("</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				      ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				  	  ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				  	");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(207,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_sort=='컴퓨터와 인터넷' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<option value=\"컴퓨터와 인터넷\" selected>컴퓨터와 인터넷 </option>\r\n");
          out.write("				  	    <option value=\"디지털 기기\">디지털 기기  </option>\r\n");
          out.write("				  	  ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(211,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.goods_sort=='디지털 기기' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<option value=\"컴퓨터와 인터넷\" >컴퓨터와 인터넷 </option>\r\n");
          out.write("				  	    <option value=\"디지털 기기\" selected>디지털 기기  </option>\r\n");
          out.write("				  	  ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(435,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(435,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/goods/modifyGoodsForm.jsp(435,5) '${imageFileList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${imageFileList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(435,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("itemNum");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			        ");
            if (_jspx_meth_c_005fchoose_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("		\r\n");
            out.write("			    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			            ");
          if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("			         ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("			       ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f3_reused = false;
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/views/admin/goods/modifyGoodsForm.jsp(437,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.fileType=='main_image' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			              <tr>\r\n");
          out.write("						    <td>메인 이미지</td>\r\n");
          out.write("						    <td>\r\n");
          out.write("							  <input type=\"file\"  id=\"main_image\"  name=\"main_image\"  onchange=\"readURL(this,'preview");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemNum.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("');\" />\r\n");
          out.write("						      ");
          out.write("\r\n");
          out.write("							  <input type=\"hidden\"  name=\"image_id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.image_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  />\r\n");
          out.write("							<br>\r\n");
          out.write("						</td>\r\n");
          out.write("						<td>\r\n");
          out.write("						  <img  id=\"preview");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemNum.count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"   width=200 height=200 src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/download.do?goods_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("						</td>\r\n");
          out.write("						<td>\r\n");
          out.write("						  &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
          out.write("						</td>\r\n");
          out.write("						 <td>\r\n");
          out.write("						 <input  type=\"button\" value=\"수정\"  onClick=\"modifyImageFile('main_image','");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.image_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.fileType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\"/>\r\n");
          out.write("						</td> \r\n");
          out.write("					</tr>\r\n");
          out.write("					<tr>\r\n");
          out.write("					 <td>\r\n");
          out.write("					   <br>\r\n");
          out.write("					 </td>\r\n");
          out.write("					</tr>\r\n");
          out.write("			         ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      _jspx_th_c_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			           <tr  id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemNum.count-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("						<td>상세 이미지");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemNum.count-1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("						<td>\r\n");
          out.write("							<input type=\"file\" name=\"detail_image\"  id=\"detail_image\"   onchange=\"readURL(this,'preview");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemNum.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("');\" />\r\n");
          out.write("							");
          out.write("\r\n");
          out.write("							<input type=\"hidden\"  name=\"image_id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.image_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  />\r\n");
          out.write("							<br>\r\n");
          out.write("						</td>\r\n");
          out.write("						<td>\r\n");
          out.write("						  <img  id=\"preview");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemNum.count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"   width=200 height=200 src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/download.do?goods_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("						</td>\r\n");
          out.write("						<td>\r\n");
          out.write("						  &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
          out.write("						</td>\r\n");
          out.write("						 <td>\r\n");
          out.write("						 <input  type=\"button\" value=\"수정\"  onClick=\"modifyImageFile('detail_image','");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.image_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.fileType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\"/>\r\n");
          out.write("						  <input  type=\"button\" value=\"삭제\"  onClick=\"deleteImageFile('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.goods_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.image_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemNum.count-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\"/>\r\n");
          out.write("						</td> \r\n");
          out.write("					</tr>\r\n");
          out.write("					<tr>\r\n");
          out.write("					 <td>\r\n");
          out.write("					   <br>\r\n");
          out.write("					 </td>\r\n");
          out.write("					</tr> \r\n");
          out.write("			         ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
